# Generated by Django 5.2.3 on 2025-06-18 06:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notes', '0002_alter_examen_ue'),
    ]

    operations = [
        migrations.AddField(
            model_name='note',
            name='ressource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='notes.ressource'),
        ),
    ]
